### PR TITLE
Add Banner to README file

### PR DESCRIPTION
**Pull request by cesaralvrz**
I added the banner to the README file with a title with align to the center. 

Also fixed a broken error for the website of Python Canarias.

### CODE REVIEW

**Review by jdevera — CHANGES_REQUESTED** [review]
**First of all, thank you for this first contribution! 🎉 🎉 🎉** 

Also, really nice banner! 😍 

I left a comment about the image URL, and here are some more that I could not attach to the right file because github will not let me comment on whole files:

- [ ] Please rename the `PyCa.png` to something more descriptive, such as `python_canarias_banner.png` (I changed the casing here just for personal preference, it's not important as long as it does not have spaces in the name)
- [ ] Please move the `assets` folder to be under the `docs` folder, this makes it extra clear it's not part of the app. Note this will require changing the path in the README too.

One meta topic: This PR comes from a conversation somewhere else and I have that context, so it's fine, but generally it is best to also include the motivation of the PR in the description itself. Not only for the reviewers of now but also for future reference.

And one topic for discussion: I noticed the banner image is larger than it ever renders in Github. Github caps this as 838px in width no matter how much bigger I make the viewport.

I think we should optimise this in a repository that is otherwise used for coding an app. If your original work on the banner comes from a vector graphics file such as SVG, It'd be great to also contribute that to the docs repository, while the image we store in this repo is the one optimised for its current use: show up in the README. What do you think?

**Comment by cesaralvrz** [comment]
The original work is also in PNG, but if you want I can add the banner in the original size to the docs repository.

**Review by jdevera — APPROVED** [review]
Thank you for the additional changes! Looks great!

**Comment by sdelquin** [comment]
Gracias @cesaralvrz por la colaboración altruista y gracias @jdevera por revisarlo y mergearlo 😄

**Pull request merged**
